# Generated by Django 4.0.7 on 2022-11-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0002_rename_last_run_pipelineexecution_started_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineexecution",
            name="reporter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pipelineexecution",
            name="runner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pipelineexecution",
            name="started",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
