# Generated by Django 4.1.3 on 2022-12-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0003_alter_pipelineexecution_reporter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("DONE", "DONE"),
                    ("CONFIG_ERROR", "CONFIG_ERROR"),
                    ("VALIDATION_ERROR", "VALIDATION_ERROR"),
                    ("RUNTIME_ERROR", "RUNTIME_ERROR"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
