# Generated by Django 4.1.3 on 2023-01-03 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0004_alter_pipelineexecution_options_and_more"),
        ("pipelines", "0004_alter_pipelineexecution_status"),
    ]

    operations = []
