# Generated by Django 4.1.3 on 2023-01-16 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0005_merge_20230103_1354"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PipelineExecution",
            new_name="PipelineResult",
        ),
        migrations.AlterUniqueTogether(
            name="pipelineresult",
            unique_together=set(),
        ),
    ]
