# Generated by Django 4.1.3 on 2023-01-16 12:08

from django.db import migrations


def clean_pipeline_and_task_results_objects(apps, schema_editor):
    apps.get_model("pipelines", "PipelineResult").objects.all().delete()
    apps.get_model("pipelines", "TaskResult").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0007_pipelineexecution_taskexecution_and_more"),
    ]

    operations = [migrations.RunPython(clean_pipeline_and_task_results_objects)]
