# Generated by Django 4.1.3 on 2023-02-09 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0016_alter_pipelineexecution_run_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineexecution",
            name="run_id",
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
