# Generated by Django 4.1.3 on 2023-02-13 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0017_alter_pipelineexecution_run_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PipelineExecution",
            new_name="OrmPipelineExecution",
        ),
        migrations.RenameModel(
            old_name="PipelineResult",
            new_name="OrmPipelineResult",
        ),
        migrations.RenameModel(
            old_name="TaskExecution",
            new_name="OrmTaskExecution",
        ),
        migrations.RenameModel(
            old_name="TaskResult",
            new_name="OrmTaskResult",
        ),
    ]
