# Generated by Django 4.1.3 on 2023-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0018_rename_pipelineexecution_ormpipelineexecution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ormpipelineexecution",
            name="completed",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ormpipelineexecution",
            name="started",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ormpipelineexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("DONE", "DONE"),
                    ("CONFIG_ERROR", "CONFIG_ERROR"),
                    ("VALIDATION_ERROR", "VALIDATION_ERROR"),
                    ("RUNTIME_ERROR", "RUNTIME_ERROR"),
                    ("CANCELLED", "CANCELLED"),
                ],
                db_index=True,
                default="PENDING",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="ormpipelineresult",
            name="completed",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ormpipelineresult",
            name="started",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ormpipelineresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("DONE", "DONE"),
                    ("CONFIG_ERROR", "CONFIG_ERROR"),
                    ("VALIDATION_ERROR", "VALIDATION_ERROR"),
                    ("RUNTIME_ERROR", "RUNTIME_ERROR"),
                    ("CANCELLED", "CANCELLED"),
                ],
                db_index=True,
                default="PENDING",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="ormtaskexecution",
            name="completed",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ormtaskexecution",
            name="started",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ormtaskexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("DONE", "DONE"),
                    ("CONFIG_ERROR", "CONFIG_ERROR"),
                    ("VALIDATION_ERROR", "VALIDATION_ERROR"),
                    ("RUNTIME_ERROR", "RUNTIME_ERROR"),
                    ("CANCELLED", "CANCELLED"),
                ],
                db_index=True,
                default="PENDING",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="ormtaskresult",
            name="completed",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ormtaskresult",
            name="started",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ormtaskresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("DONE", "DONE"),
                    ("CONFIG_ERROR", "CONFIG_ERROR"),
                    ("VALIDATION_ERROR", "VALIDATION_ERROR"),
                    ("RUNTIME_ERROR", "RUNTIME_ERROR"),
                    ("CANCELLED", "CANCELLED"),
                ],
                db_index=True,
                default="PENDING",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="valuestore",
            name="key",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="valuestore",
            name="run_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
