# Generated by Django 4.1.3 on 2023-02-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0019_alter_ormpipelineexecution_completed_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ValueStore",
        ),
        migrations.AlterField(
            model_name="pipelinelog",
            name="context_type",
            field=models.CharField(
                choices=[
                    ("PipelineExecution", "PipelineExecution"),
                    ("PipelineExecution", "PipelineResult"),
                    ("PipelineExecution", "TaskExecution"),
                    ("PipelineExecution", "TaskResult"),
                ],
                max_length=255,
            ),
        ),
    ]
