# Generated by Django 4.0.7 on 2022-09-30 13:45

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("reference", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=50)),
                ("contract_start_date", models.DateTimeField()),
                ("contract_end_date", models.DateTimeField(null=True)),
                ("product_cloud", models.BooleanField(default=False)),
                ("product_connectivity", models.BooleanField(default=False)),
                ("product_licenses", models.BooleanField(default=False)),
                ("product_managed_services", models.BooleanField(default=False)),
                ("product_backup", models.BooleanField(default=False)),
                ("product_hardware", models.BooleanField(default=False)),
                ("faults", models.IntegerField(default=0)),
                ("sla_breaches", models.IntegerField(default=0)),
                ("ownership_changes", models.IntegerField(default=0)),
                (
                    "recurring_revenue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "non_recurring_revenue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
