# Generated by Django 4.0.7 on 2022-10-03 09:48

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("churn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("months_as_customer", models.IntegerField()),
                ("product_cloud", models.BooleanField(default=False)),
                ("product_connectivity", models.BooleanField(default=False)),
                ("product_licenses", models.BooleanField(default=False)),
                ("product_managed_services", models.BooleanField(default=False)),
                ("product_backup", models.BooleanField(default=False)),
                ("product_hardware", models.BooleanField(default=False)),
                ("faults", models.IntegerField(default=0)),
                ("sla_breaches", models.IntegerField(default=0)),
                ("ownership_changes", models.IntegerField(default=0)),
                (
                    "non_recurring_revenue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
