# Generated by Django 4.0.7 on 2022-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo_app", "0002_parameter_vehicle_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="value",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
