# Generated by Django 4.0.7 on 2022-10-10 14:53

import datorum_pipelines.status
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('pipeline_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('CONFIG_ERROR', 'CONFIG_ERROR'), ('VALIDATION_ERROR', 'VALIDATION_ERROR'), ('RUNTIME_ERROR', 'RUNTIME_ERROR'), ('CANCELLED', 'CANCELLED')], max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('task_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('CONFIG_ERROR', 'CONFIG_ERROR'), ('VALIDATION_ERROR', 'VALIDATION_ERROR'), ('RUNTIME_ERROR', 'RUNTIME_ERROR'), ('CANCELLED', 'CANCELLED')], default=datorum_pipelines.status.PipelineTaskStatus['PENDING'], max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
