# Generated by Django 4.0.7 on 2022-10-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datorum_pipelines", "0003_alter_taskresult_data_alter_taskresult_payload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskresult",
            old_name="data",
            new_name="input_data",
        ),
        migrations.RenameField(
            model_name="taskresult",
            old_name="payload",
            new_name="output_data",
        ),
        migrations.AlterField(
            model_name="taskresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("DONE", "DONE"),
                    ("CONFIG_ERROR", "CONFIG_ERROR"),
                    ("VALIDATION_ERROR", "VALIDATION_ERROR"),
                    ("RUNTIME_ERROR", "RUNTIME_ERROR"),
                    ("CANCELLED", "CANCELLED"),
                ],
                max_length=255,
            ),
        ),
    ]
