# Generated by Django 4.0.7 on 2022-10-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datorum_pipelines", "0004_rename_data_taskresult_input_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.TextField(unique=True)),
                ("last_run", models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="taskresult",
            options={},
        ),
        migrations.RenameField(
            model_name="taskresult",
            old_name="identifier",
            new_name="run_id",
        ),
        migrations.AddField(
            model_name="pipelinelog",
            name="run_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="run_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="taskresult",
            unique_together={("task_id", "run_id")},
        ),
    ]
