# Generated by Django 4.0.7 on 2022-10-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "datorum_pipelines",
            "0005_pipelineexecution_alter_taskresult_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="pipelineexecution",
            old_name="slug",
            new_name="pipeline_id",
        ),
        migrations.RemoveField(
            model_name="taskresult",
            name="created",
        ),
        migrations.RemoveField(
            model_name="taskresult",
            name="modified",
        ),
        migrations.AddField(
            model_name="taskresult",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskresult",
            name="started",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
