# Generated by Django 4.0.7 on 2022-10-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datorum_pipelines', '0006_rename_slug_pipelineexecution_pipeline_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='pipeline_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
