# Generated by Django 4.0.7 on 2022-10-12 12:28

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("datorum_pipelines", "0007_taskresult_pipeline_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("pipeline_id", models.CharField(max_length=255)),
                ("run_id", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=255)),
                ("value", models.JSONField(blank=True, null=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="taskresult",
            name="output_data",
        ),
        migrations.AddField(
            model_name="taskresult",
            name="config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pipelineexecution",
            name="pipeline_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
