# Generated by Django 4.0.7 on 2022-10-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datorum_pipelines", "0008_valuestore_remove_taskresult_output_data_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="valuestore",
            options={},
        ),
        migrations.AddField(
            model_name="taskresult",
            name="task_slug",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="valuestore",
            unique_together={("pipeline_id", "run_id", "key")},
        ),
    ]
