# Generated by Django 4.0.7 on 2022-10-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "datorum_pipelines",
            "0009_alter_valuestore_options_taskresult_task_slug_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskresult",
            old_name="task_slug",
            new_name="pipeline_task",
        ),
    ]
