# Generated by Django 4.0.7 on 2022-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datorum_pipelines", "0010_rename_task_slug_taskresult_pipeline_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="pipeline_task",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
